### ISSUE TITLE
Вложенное меню

### ISSUE THREAD

**Issue by foxhable** [momo-hash1/kzgu#26]
- Нужно забрать у вложенных `ul` задний фон, т.к. если у детей будет больше элементов, то из-за `min-height: 100%;` выглядеть это будет так

![image](https://user-images.githubusercontent.com/36298346/230721082-3f2ec2d1-0949-4183-a01c-52acf077cd17.png)
https://github.com/momo-hash1/kzgu/blob/a03ee8fa426f18305243d5cb960b83ba53c1e9e2/src/style/components/_dropdown.scss#L57-L59
https://github.com/momo-hash1/kzgu/blob/a03ee8fa426f18305243d5cb960b83ba53c1e9e2/src/style/components/_dropdown.scss#L47-L49
https://github.com/momo-hash1/kzgu/blob/a03ee8fa426f18305243d5cb960b83ba53c1e9e2/src/style/components/_dropdown.scss#L19-L21

<br>

- Цвета заднего фона и при наведении не как в макете.

- Я знаю, что до этого попросил дать `ul` отступы, но тогда не учел про задний фон и минимальную высоту. Мы отбираем задний фон у `ul`, поэтому появится проблема с падингами, их нужно убрать и дать `li` элементам.

Здесь отбираем `padding`
https://github.com/momo-hash1/kzgu/blob/a03ee8fa426f18305243d5cb960b83ba53c1e9e2/src/style/components/_dropdown.scss#L10-L14
Тут даем
```scss
li {
  padding: 0 4px;

  &:first-child {
    padding-top: 8px;
  }

  &:last-child {
    padding-bottom: 8px;
  }
}
```
Задний фон, который мы забрали, нужно дать так же `li` элементам, и при наведении давать задний фон `a` элементу внутри. Для первого вложенного меню это будет выглядеть так:
```scss
li {
  background-color: #E6EBF2;

  &:hover > a {
    background-color: #D9E0EB;
  }
}
```
