### ISSUE TITLE
Каталог со слайдером

### ISSUE THREAD

**Issue by foxhable** [momo-hash1/kzgu#5]
- У карточек заголовки тэг поменяй с `h1` на `div`
- Между текстом состояния и картинкой должно быть расстояние в `13px`

![image](https://user-images.githubusercontent.com/36298346/227984117-47bf1dc1-b802-4fa9-8d7d-df36e04e2e58.png)

- "Узнать цену" лучше сделать по-другому. У слайдера добавить снизу отступ размером в кнопку. Кнопку сделать со стилями
```css
button {
  position: absolute;
  top: 100%;
  left: 0;
  visibility: hidden;
  opacity: 0;
  transition-timing-function: ease-in-out;
  transition-duration: 300ms;
  transition-property: visibility, opacity;
}
```
не забудь стили с отступами и задним фоном. Карточку сделать `position: relative;`. Далее при наведении на карточку следующие стили
```css
.card:hover button {
  visibility: visible;
  opacity: 1;
}
```
это избавит от трех проблем:
1. Резкая анимация
2. Сдвиг всего документа снизу
3. Сдвиг сетки в каталоге, когда включен вид плиткой
